apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-appsettingv1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev-appsettingv1
  template:
    metadata:
      labels:
        app: dev-appsettingv1
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: dev-appsettingv1
          image: 471112842990.dkr.ecr.ap-south-1.amazonaws.com/dev-appsetting-ecr-repo:latest
          ports:
            - containerPort: 9000 # Expose port in the container
---
apiVersion: v1
kind: Service
metadata:
  name: dev-appsetting-service
spec:
  type: NodePort
  selector:
    app: dev-appsettingv1
  ports:
    - protocol: TCP
      port: 9000        # The port exposed by the service
      targetPort: 9000  # The port the application listens on in the container
      nodePort: 30008   # The NodePort that will be used to access the service
