apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-appsetting
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev-appsetting
  template:
    metadata:
      labels:
        app: dev-appsetting
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: dev-appsetting
          image: 471112842990.dkr.ecr.ap-south-1.amazonaws.com/dev-appsetting-ecr-repo:latest
          ports:
            - containerPort: 9090 # Expose por in the container
---
apiVersion: v1
kind: Service
metadata:
  name: dev-appsetting-service
spec:
  type: NodePort
  selector:
    app: dev-appsetting
  ports:
    - protocol: TCP
      port: 9090      # The port exposed by the service
      targetPort: 9090 # The port the application listens on in the container