export const IDENTIFIER = {
  ICountryRepository: Symbol.for("ICountryRepository"),
  ICountryService: Symbol.for("ICountryService"),
  CountryController: Symbol.for("CountryController"),
  ICountryDocument: Symbol.for("ICountryDocument"),
  ICountrySeedRepository: Symbol.for("ICountrySeedRepository"),
  ICountrySeedService: Symbol.for("ICountrySeedService"),
  ILanguageSeedRepository: Symbol.for("ILanguageSeedRepository"),
  ILanguageSeedService: Symbol.for("ILanguageSeedService"),
  IApplicationSeedRepository: Symbol.for("IApplicationSeedRepository"),
  IApplicationSeedService: Symbol.for("IApplicationSeedService"),
  SeedDataController: Symbol.for("SeedDataController"),
  IMessageBrokerService: Symbol.for("IMessageBrokerService"),
  IDatabaseProvider: Symbol.for("IDatabaseProvider"),
  ICategoryRepository: Symbol.for("ICategoryRepository"),
  ICategoryService: Symbol.for("ICategoryService"),
  CategoryController: Symbol.for("CategoryController"),
};
