class RabbitMQPublishers {
  static APPSETTING_EXCHANGE = class {
    static EXCHANGE_NAME: string = "APPSETTING_EXCHANGE";
    static EVENT_CREATE_COUNTRY: string = "APPSETTING_EVENT_CREATE_COUNTRY";
    static EVENT_UPDATE_COUNTRY: string = "APPSETTING_EVENT_UPDATE_COUNTRY";
    static EVENT_DELETE_COUNTRY: string = "APPSETTING_EVENT_DELETE_COUNTRY";
    static EVENT_CREATE_CATEGORY: string = "APPSETTING_EVENT_CREATE_CATEGORY";
    static EVENT_UPDATE_CATEGORY: string = "APPSETTING_EVENT_UPDATE_CATEGORY";
    static EVENT_DELETE_CATEGORY: string = "APPSETTING_EVENT_DELETE_CATEGORY";
  };

  static CONTENT_EXCHANGE = class {
    static EXCHANGE_NAME: string = "CONTENT_EXCHANGE";
    static EVENT_CREATE_VIDEO: string = "CONTENT_EVENT_CREATE_VIDEO";
    static EVENT_UPDATE_VIDEO: string = "CONTENT_EVENT_UPDATE_VIDEO";
    static EVENT_DELETE_VIDEO: string = "CONTENT_EVENT_DELETE_VIDEO";
  };

  static MILESTONE_EXCHANGE = class {
    static EXCHANGE_NAME: string = "MILESTONE_EXCHANGE";
  };
}

export default RabbitMQPublishers;
